#!/usr/bin/env bash
# Point ComfyUI at the network volume, provision models, launch.
set -euo pipefail

WORKSPACE="${WORKSPACE:-/workspace}"
MODELS_DIR="${MODELS_DIR:-$WORKSPACE/models}"
COMFY_DIR="${COMFY_DIR:-/opt/ComfyUI}"
COMFY_PORT="${COMFY_PORT:-8188}"

log() { printf '[entrypoint] %s\n' "$*"; }

is_true() {
    case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
        1|true|yes|y|on) return 0 ;;
        *) return 1 ;;
    esac
}

# --- 1. is the volume actually attached? -----------------------------------
if ! awk -v p="$WORKSPACE" '$2 == p { found = 1 } END { exit !found }' /proc/mounts; then
    log "WARNING: $WORKSPACE is not a mountpoint."
    log "WARNING: everything downloaded now lives in the container and dies with it."
    log "WARNING: attach your network volume with mount path $WORKSPACE, or you will"
    log "WARNING: pay to download ~35 GB again on the next boot."
fi

# --- 2. layout -------------------------------------------------------------
mkdir -p \
    "$WORKSPACE/output" \
    "$WORKSPACE/input" \
    "$WORKSPACE/user/default/workflows" \
    "$WORKSPACE/custom_nodes" \
    "$MODELS_DIR"

# --- 3. tell ComfyUI where the models are ----------------------------------
cat > "$COMFY_DIR/extra_model_paths.yaml" <<YAML
# Generated by entrypoint.sh on every boot — edit MODELS_DIR, not this file.
runpod:
    base_path: $MODELS_DIR
    is_default: true
    checkpoints: checkpoints
    diffusion_models: diffusion_models
    unet: diffusion_models
    clip: clip
    text_encoders: clip
    clip_vision: clip_vision
    vae: vae
    loras: loras
    controlnet: controlnet
    upscale_models: upscale_models
    embeddings: embeddings
    style_models: style_models
    # Nodes installed through ComfyUI Manager land here and survive a restart.
    custom_nodes: $WORKSPACE/custom_nodes
YAML
log "wrote $COMFY_DIR/extra_model_paths.yaml (base_path=$MODELS_DIR)"

# --- 4. seed the bundled workflows, never clobbering edits ------------------
shopt -s nullglob
for wf in /opt/workflows/*.json; do
    name="$(basename "$wf")"
    dest="$WORKSPACE/user/default/workflows/$name"
    if [ -e "$dest" ]; then
        log "workflow $name already on the volume, leaving your copy alone"
    else
        cp "$wf" "$dest"
        log "seeded workflow $name"
    fi
done
shopt -u nullglob

# --- 5. models -------------------------------------------------------------
if is_true "${SKIP_PROVISION:-false}"; then
    log "SKIP_PROVISION is set — not checking or downloading any models"
else
    python /opt/scripts/provision.py \
        || log "WARNING: provisioning reported an error; starting ComfyUI anyway"
fi

# --- 6. one-off pip packages, for trying a node without a rebuild -----------
if [ -n "${PIP_INSTALL:-}" ]; then
    log "PIP_INSTALL: $PIP_INSTALL"
    # shellcheck disable=SC2086
    pip install $PIP_INSTALL || log "WARNING: PIP_INSTALL failed, continuing"
fi

# --- 7. requirements for volume-installed custom nodes ---------------------
shopt -s nullglob
for req in "$WORKSPACE"/custom_nodes/*/requirements.txt; do
    log "installing requirements for $(basename "$(dirname "$req")")"
    pip install -r "$req" || log "WARNING: requirements failed for $req, continuing"
done
shopt -u nullglob

# --- 8. go ------------------------------------------------------------------
cd "$COMFY_DIR"
log "starting ComfyUI on 0.0.0.0:$COMFY_PORT"
# shellcheck disable=SC2086
exec python main.py \
    --listen 0.0.0.0 \
    --port "$COMFY_PORT" \
    --output-directory "$WORKSPACE/output" \
    --input-directory "$WORKSPACE/input" \
    --user-directory "$WORKSPACE/user" \
    ${COMFY_ARGS:-}
